### ISSUE TITLE
Beat Detection at Train Time?

### ISSUE THREAD

**Issue by geoffreyangus** [echonet/dynamic#12]
Hello all,

First I want to congratulate you on this paper, it is well written and clearly demonstrates clinical value. One aspect of the paper that I must have missed has to do with how the 3D CNN is trained. From what I can tell, it produces a single classification (the ejection fraction) for the entire clip, which itself is comprised of multiple ventricular contractions. I believe that during test time, a single ventricular contraction is identified using the segmentation model, and then fed into the classifier. This process is repeated for each ventricular contraction contained in the clip, and then the classifier's predictions are averaged. If I understand correctly, you are inputting the entire clip during training, but inputting the clip in fragments during evaluation. Is this something that is accounted for or is this handled naturally by the model?

**Comment by douyang** [comment]
During training, dataloader in the notebook is sampling one clip of defined length within the video. During test time, set clips="all" for a prediction per frame. The R script integrates the output from the segmentation model that identifies each beat and averages across beats.
