### ISSUE TITLE
Object 'highVar' not found

### ISSUE THREAD

**Issue by Beep-Boop-Bopa** [echonet/dynamic#14]
Issue with: scripts/beat_analysis.R

There were a couple of issues that I faced while trying to run this file. I was able to resolve all of them except this one:

![image](https://user-images.githubusercontent.com/42900802/94351695-e1fc4e80-0029-11eb-859d-56993643c23a.png)

The issue is at Line # 72 with this command: beatByBeatAnalysis <- beatByBeatAnalysis[beatByBeatAnalysis$Filename %in% highVar,]

Could u help? What am I missing here? The word 'highVar' appears only once in the entirety of this git repo,

**Comment by douyang** [comment]
HighVar was just the subset of videos with STD of >2.5 
The code should work with line 72 commented out.

It was used to generate subanalysis plots:

beatByBeatAnalysis <- beatByBeatAnalysis %>% group_by(Filename) %>% mutate(minVal = min(relativePrediction) - 5, 
 				maxVal = max(relativePrediction) + 5, meanBeat = mean(relativePrediction), stdBeat =  sd(relativePrediction))

.....

highVar <- ggplot(beatByBeatAnalysis[!is.na(beatByBeatAnalysis$stdBeat) & beatByBeatAnalysis$stdBeat > 2.5,], aes(x = reorder(Filename, meanBeat ))) +
geom_rect(xmin = -Inf, xmax = Inf, ymin = -5, ymax = 5, size = 45, fill = "gray90") +
geom_hline(yintercept = 0) +geom_hline(yintercept = 5, linetype = "longdash") + geom_hline(yintercept = -5, linetype = "longdash") +
geom_linerange(aes(ymin = minVal, ymax = maxVal), color = "grey") +
geom_point(aes(y = relativePrediction, color = stdBeat > 2.5))  + theme_bw() + xlab("High Variance Patients") + ylab("Difference from Human Assessment of EF") +
theme(axis.text.x = element_blank(), axis.ticks = element_blank(), legend.position = "none") + scale_x_discrete(breaks = NULL) +  geom_hline(yintercept = 0) +
geom_hline(yintercept = 5, linetype = "longdash") + geom_hline(yintercept = -5, linetype = "longdash") +
scale_y_continuous(breaks = c(-30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30, 35, 40)) + scale_color_brewer(palette = "Set1", direction = -1) + ylim(-30,30)
highVar

**Comment by Beep-Boop-Bopa** [comment]
Hey, thanks for the quick reply. I commented out line # 72 and have run into another problem at line # 82:

![image](https://user-images.githubusercontent.com/42900802/94352442-fee94f80-0032-11eb-96e7-b9159a3777ea.png)

Do you have any suggestions for what I should do here?

**Comment by douyang** [comment]
This depends on your R environment and what libraries are loaded. 
The function 'summarize' is overloaded in the package dplyr and plyr. 

https://stackoverflow.com/questions/26106146/why-does-summarize-or-mutate-not-work-with-group-by-when-i-load-plyr-after-dp

You need to change summarize(meanPred = mean(V3)) to dplyr::summarize(meanPred = mean(V3))

**Comment by Beep-Boop-Bopa** [comment]
I fixed the issue. The issue was that the R code assumes that any dataframe with FileNames has the column named like "Filename", but there are some data frames where it is spelled as "FileName". The issue was in line # 83, not # 82.
