### ISSUE TITLE
How to use sub-sampled clips around the lowest segmentation Areas for EF calculation?

### ISSUE THREAD

**Issue by Beep-Boop-Bopa** [echonet/dynamic#15]
There are some issues with the InitializationNotebook.ipynb:
1. Some EchoNet functions haven't been called properly. I had to modify the code to make them work. 
2. Secondly, the Segmentation model isn't being initialized and used for segmentation. I was able to mitigate this issue as well by looking at this [git pull](https://github.com/echonet/dynamic/pull/11).

3. Lastly, **and more importantly**, I don't think the code is using the segmentation areas to generate subsampled clips and calculate the EF on that. Am I right with this judgment? Could you provide guidelines/python-code on how to go about generating the subsampled clips?

**Comment by douyang** [comment]
Thanks for your suggestion, please feel free to suggest git pulls for corrections/modifications. The InitializationNotebook was an early draft and will be updated when pulls can be reviewed. 

The subsampled clips are generated by the dataloader. The integration of clips by beat from segmentation is done in beat_by_beat_analysis.R.
