### ISSUE TITLE
The generation of segmentation maps

### ISSUE THREAD

**Issue by YunhuaZhang** [echonet/dynamic#3]
Thank you very much for releasing the code and the dataset. 
When I run your code to generate the segmentation maps, it only produces 10024 videos with segmentation maps, while the dataset has 10030 videos in total. Why there is a difference?

**Comment by douyang** [comment]
Thanks for the comment. After review, it looks like there are 6 videos without corresponding human tracings in the publicly released file. We will correct this in the next iteration of the public dataset. The code (and results) should be robust to the small number of missing segmentations for training.
