### ISSUE TITLE
Error trying to convert DICOM to AVI

### ISSUE THREAD

**Issue by JohanWedenfelt** [echonet/dynamic#36]
I'm trying to convert a DICOM clip to an AVI file, but it doesn't work. 
When debugging, line 14 in cell beginning with 
`def makeVideo(fileToProcess, destinationFolder):`
I'm handed the following error messege:
`Exception has occurred: IndexError x
index 0 is out of bounds for axis 0 with size 0
File "D:\pythonprojects\echonet\dynamic\scripts\convertDICOM.py"
yCrop = np.where(mean<1[0][0]`

testarray value begins with [ 0, 127, 127], and 
mean is array([84.908.......

Are there special requirements on the input DICOM clips? This is a clip of 1024 columns and 768 rows and about 130 frames.

**Comment by douyang** [comment]
Dicoms can be stored in three channel or black and white single channel, which will require modifications to the code.
