### ISSUE TITLE
Possible confidence interval issue

### ISSUE THREAD

**Issue by dfpasdel** [echonet/dynamic#71]
https://github.com/echonet/dynamic/blob/108518f305dbd729c4dca5da636601ebd388f77d/echonet/utils/__init__.py#L148

You are here calculating a 90% confidence interval with bootstrapping. This is at least how I understand it since 0.95-0.05=0.9. Tell me if I am wrong.

What makes me confused is that in your article, you state having calculated 95% confidence intervals for the dice score: "the Dice similarity coefficient for the end-systolic tracing was 0.903 (95% confidence interval of 0.901–0.906)".

Could you clarify this for me and the whole research community?

**Comment by echonet** [comment]
DICE is similarly bootstrapped. There is a DICE score for each image and segmentation comparison. The 5% to 95% quantile DICE is described as a confidence interval in addition to the mean DICE.
