### ISSUE TITLE
Bad Segmentation Masks on Some Data

### ISSUE THREAD

**Issue by fadamsyah** [echonet/dynamic#74]
Hi @douyang , thank you so much for maintaining this repository.

I trained a model and then did a prediction on test dataset. However I noticed that there are some samples that have bad segmentation masks. May I ask you to confirm this issue? Do you also get the same bad segmentation masks on the following data/video? Thank you again!

508efe58925d.avi
![bad_0X1CF4B07994B62DBB](https://user-images.githubusercontent.com/56474352/211713584-70d17841-5f1a-4a0b-903a-508efe58925d.png)

c4a056b2af8a.avi
![bad_0X43DE853BD6E0C849](https://user-images.githubusercontent.com/56474352/211713590-951cd492-e2b0-4b5e-aaac-c4a056b2af8a.png)

edd3b73c00dd.avi
![bad_0X53BD50EB0C43D30D](https://user-images.githubusercontent.com/56474352/211713594-81925906-84a3-463d-893d-edd3b73c00dd.png)

**Comment by douyang** [comment]
This can occur when the frame number is not being disambiguated. There can be multiple tracings per video and when they overlap, the polygon segmentation can look weird. Check that not all coordinates from a video are being plotted and they are split by frame num. There might be <10 where there are multiple systole or diastole segmentations that need to be handled individually.
