### ISSUE TITLE
the Echo dataset cannot be used in a dataloader 

### ISSUE THREAD

**Issue by xiaojinmao-code** [echonet/dynamic#8]
Hello, I am referring to your code, but I have been making an error：AttributeError: Can't pickle local object 'run.<locals>.collate_fn'，my system is win10, I noticed that you have a function involved in this kind of problem, could you please tell me how to use it and modify it, I don't quite understand, thank you！

**Comment by bryanhe** [comment]
Can you pull the code and see if it's fixed now?

**Comment by xiaojinmao-code** [comment]
I haven't solved the problem yet. It was an error running the segmentation.py,I searched for the wrong reason, which may be the reason of multi-process in win10 platform,AttributeError: Can't pickle local object 'run..collate_fn'.......So I noticed that you have a function in your code that might solve this problem, but I don't know how to use it
``def _defaultdict_of_lists():
    """Returns a defaultdict of lists.
[
    This is used to avoid issues with Windows (if this function is anonymous,
    the Echo dataset cannot be used in a dataloader).
    """

    return collections.defaultdict(list)

**Comment by xiaojinmao-code** [comment]
`100%|██████████| 16/16 [00:12<00:00,  1.33it/s]
  0%|          | 0/128 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:/PyCharm 2019.3.3/ultarsound cardiogram/echonet/utils/segmentation.py", line 471, in <module>
    run(modelname="deeplabv3_resnet50", save_segmentation=True, pretrained=False)
  File "D:/PyCharm 2019.3.3/ultarsound cardiogram/echonet/utils/segmentation.py", line 267, in run
    for (x, (filenames, large_index, small_index), length) in tqdm.tqdm(dataloader):
  File "D:\Anaconda3\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'run.<locals>.collate_fn'
  0%|          | 0/128 [00:00<?, ?it/s]`

**Comment by xiaojinmao-code** [comment]
I haven't solved the problem yet. It was an error running the segmentation.py,I searched for the wrong reason, which may be the reason of multi-process in win10 platform,AttributeError: Can't pickle local object 'run..collate_fn'.......So I noticed that you have a function in your code that might solve this problem, but I don't know how to use it
`def _defaultdict_of_lists():
    """Returns a defaultdict of lists.
[
    This is used to avoid issues with Windows (if this function is anonymous,
    the Echo dataset cannot be used in a dataloader).
    """

    return collections.defaultdict(list)`

**Comment by bryanhe** [comment]
I updated the code, which should fix the error.

You can run
```git pull```
in your code directory to get the updated version.

**Comment by xiaojinmao-code** [comment]
thank you very much!You are very powerful!
