### ISSUE TITLE
Echonet

### ISSUE THREAD

**Issue by Alicoo1907** [echonet/dynamic#80]
Does echonet package removed from pip ?

**Comment by alexgcsa** [comment]
I am currently experiencing the same issue here.
I can't find the package.

**Comment by adikrishnanucd** [comment]
Has there been a fix for this issue? @alexgcsa @Alicoo1907

**Comment by Alicoo1907** [comment]
@adikrishnanucd Unfortunately, same "ERROR: No matching distribution found for echonet" . I wonder if the owners removed the package?

**Comment by adikrishnanucd** [comment]
@Alicoo1907 and @alexgcsa Thank you both very much for the clarification. I figured out that I needed to install the repository with pip. The problem has been resolved for me.

Just to clarify, to get rid of this issue:

1. Navigate to the cloned repository (i.e. dynamic/ folder)
2. Run `pip install .`
3. The echonet package should be installed and you can very by checking your installed Python packages with `pip list` or `pip show echonet`.

Thank you very much.

**Comment by Alicoo1907** [comment]
Oh, I just tried to install echonet with pip. I must have read or misunderstood. I'm closing the issue. Thanks both @alexgcsa @adikrishnanucd
