### ISSUE TITLE
Is it possible to get the trained best.pt?

### ISSUE THREAD

**Issue by FredySu** [echonet/dynamic#84]
Hello authors,

i am working with a project with similar A4C videos, and i would like to use echonet as a pretrained model.
However, our computing resources is limited, and i wonder if it is possible to get a  trained model directly. I mean, will the best model.pt on your dataset be public?

**Comment by echonet** [comment]
> Hello authors,
> 
> 
> 
> i am working with a project with similar A4C videos, and i would like to use echonet as a pretrained model.
> 
> However, our computing resources is limited, and i wonder if it is possible to get a  trained model directly. I mean, will the best model.pt on your dataset be public?

It is shared as a release.

**Comment by FredySu** [comment]
Thanks a lot! I noticed that now.
